name: "Setup Node"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: yarn

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
